# Generated by Django 5.1.4 on 2024-12-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagraound', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='anomalylog',
            table='AnomalyLog',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='Conversation',
        ),
        migrations.AlterModelTable(
            name='iotdata',
            table='IoTData',
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
